# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

alias l="ls -alFh";
alias openFileSystemToWeb='ifconfig | grep inet; python -m SimpleHTTPServer 8998;';
alias gs="git status";
alias gitx="/Applications/GitX.app/Contents/MacOS/GitX .";

source ~/.functions/colors.zsh;
source ~/.functions/tail-in-colors.zsh
source ~/.functions/mvn-in-colors.zsh
alias tail="tail-in-colors";
alias mvn="mvn-in-colors";
alias mvnDebug="mvn-debug-in-colors";

eval "$(rbenv init -)"

if [ -f ~/.bash_prompt ]; then
  . ~/.bash_prompt
fi
