# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

eval "$(rbenv init -)"

if [ -f ~/.bash-prompt ]; then
  . ~/.bash-prompt
fi

if [ -f ~/.env-vars ]; then
  . ~/.env-vars
fi
if [ -f ~/.env-vars.secrets ]; then
  . ~/.env-vars.secrets
fi
