execute pathogen#infect()

if $VIM_PLUGINS != 'NO'
  runtime! autoload/pathogen.vim
  if exists('g:loaded_pathogen')
    execute pathogen#infect('~/.vimbundles/{}', '~/.vim/bundle/{}')
  endif
endif

syntax on
filetype plugin indent on

set visualbell

set wildmenu
set wildmode=list:longest,full

set splitright
set splitbelow

set hidden

set guifont=Monaco:h16
set guioptions-=T guioptions-=e guioptions-=L guioptions-=r
set shell=bash

augroup vimrc
  autocmd!
  autocmd GuiEnter * set columns=120 lines=70 number
augroup END

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

set colorcolumn=80
set number
set spell spelllang=en_us
set exrc
set foldmethod=indent
set foldlevel=5

filetype plugin indent on
au FileType cucumber setl sw=2 sts=2 et
set shiftwidth=2
set tabstop=2
set expandtab

set ignorecase
set smartcase
set hlsearch
set incsearch
nmap <silent> // :nohlsearch<CR>

let g:markdown_fenced_languages = ['html', 'vim', 'ruby', 'python', 'bash=sh']

set background=dark
colorscheme solarized

set runtimepath^=~/.vim/bundle/ag.vim

if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

hi Search ctermfg=NONE ctermbg=NONE cterm=bold,underline

autocmd BufRead *.md nmap <buffer> <leader>t :<C-U>w \| call Send_to_Tmux("chrome http://localhost:4000/ \n")<CR>
autocmd BufRead * vmap <buffer> \\ <Plug>SendSelectionToTmux
autocmd BufEnter *.png,*.jpg,*gif exec "! imgcat ".expand("%") | :bw

silent !mkdir ~/.vim/.backup ~/.vim/.swp ~/.vim/.undo > /dev/null 2>&1

set undodir=~/.vim/.undo//
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//
