export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

file="$HOME/.sh_exports";  if [[ -s $file ]] ; then source $file ; fi
file="$HOME/.sh_aliases";  if [[ -s $file ]] ; then source $file ; fi
file="$HOME/.zshrc.local"; if [[ -s $file ]] ; then source $file ; fi

export ERL_AFLAGS="-kernel shell_history enabled"
eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH=/Applications/Android\ Studio.app/Contents/jbr/Contents/Home/bin:$PATH
eval "$(/Users/vnegrisolo/.local/bin/mise activate zsh)"
