export ZSH=/Users/vnegrisolo/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(
  git
)
source $ZSH/oh-my-zsh.sh

file="$HOME/.sh_exports";  if [[ -s $file ]] ; then source $file ; fi
file="$HOME/.sh_aliases";  if [[ -s $file ]] ; then source $file ; fi
file="$HOME/.zshrc.local"; if [[ -s $file ]] ; then source $file ; fi

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
