#!/usr/bin/env bash
#MISE dir="{{cwd}}"
#MISE description="Reset database"
set -xeuo pipefail

[ -f ".env" ] && source .env;

run() {
  if [[ -f "mix.exs" ]]; then
    mix do ecto.reset + ecto.seeds + ecto.dump
    MIX_ENV=test mix ecto.reset
  fi

  if [[ -f "Gemfile" ]]; then
    bundle exec rails db:reset
  fi
}

run
